In [2]:
import numpy as np

In [3]:
#initialization

array_a = np.array([1,2,3,4,5])

In [4]:
array_a

array([1, 2, 3, 4, 5])

In [6]:
#numpy is homogeneous 
array_b = np.array([1,2,3,'hello'])

In [9]:
#it will change to 1,2,3 into strings
#array has dimensions: how to find it out

print(array_a.shape)

(5,)


In [10]:
#it returns a tuple and one integer as it is a one-dimentional array

array_b = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [11]:
array_b

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
#lets get the shape
print(array_b.shape)

(2, 5)


In [14]:
array_c = np.array([[1,2,3,4],[1,2,3],[1,2]])

In [15]:
print(array_c.shape)

(3,)


In [17]:
array_c

array([list([1, 2, 3, 4]), list([1, 2, 3]), list([1, 2])], dtype=object)

In [21]:
a = [1,2,3]
b= [1,2,3]
c= [1.5,2,3]

In [22]:
array_d = np.array([a,b,c])

In [23]:
array_d

array([[1. , 2. , 3. ],
       [1. , 2. , 3. ],
       [1.5, 2. , 3. ]])

In [24]:
#it converted all other values into float

In [25]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [26]:
array_d

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [27]:
array_d.shape

(2, 5)

In [28]:
array_a = np.array([[1,2,3],[4,5,6]])

In [29]:
#size and tribute 2*3 
array_a.size

6

In [30]:
#lets try to change the shape 
array_b = array_a.reshape(1,6)

In [31]:
array_b

array([[1, 2, 3, 4, 5, 6]])

In [32]:
array_b = array_a.T

In [33]:
array_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
array_b[0][0]

1

In [36]:
array_b[0]

array([1, 4])

In [38]:
#get only one row
array_b[:,1]

array([4, 5, 6])

In [39]:
 array_A = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

In [40]:
array_B = array_A.reshape(2,8)

In [41]:
array_B

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [42]:
array_C = array_B.T

In [43]:
array_C

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [45]:
array_A

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
print(array_A[0],array_A[1])

[1 2 3 4] [4 5 6 7]


In [48]:
array_A[-1]

array([12, 13, 14, 15])

In [50]:
array_A[3][-1]

15

In [51]:
array_A[-1][-1]

15

In [54]:
array_A[:,1]

array([ 2,  5,  9, 13])

In [55]:
array_A[2][2]

10

In [56]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#we can change the integer to any other datatype
array_a = np.array([[1,2,3],[4,5,6]], dtype=float)

In [58]:
array_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [59]:
#creating an array with zero values
array_b = np.zeros((3,3))

In [60]:
array_b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
array_b = np.ones((3,3))

In [62]:
array_b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
array_b = np.full((3,3),3)

In [64]:
array_b

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [68]:
array_e = np.random.random((3,4))

In [66]:
array_e

array([[0.04162454, 0.13353023, 0.65844793, 0.83100698],
       [0.79977281, 0.85787009, 0.79858835, 0.9650114 ],
       [0.33826158, 0.35982923, 0.53742687, 0.42456201]])

In [80]:
array_a = np.array([32766,3277,32768], dtype=np.int16)

In [77]:
#get the dtype of the array
array_a.dtype

dtype('float64')

In [81]:
array_a

array([ 32766,   3277, -32768], dtype=int16)

In [84]:
array_b = np.array([-1,0,1], dtype=np.uint16)

In [85]:
array_b

array([65535,     0,     1], dtype=uint16)

In [87]:
row1 = [1,2,3,4,5]
row2 = [6,7,8,9,10]
row3 = [11,12,13,14,15]
row4 = [16,17,18,19,20]
row5 = [21,22,23,24,25]

Array_AB = np.array([row1,row2,row3,row4,row5])

In [88]:
Array_AB

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [92]:
Array_AB[:,2:4:1]#start:ending value:stepSize

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

In [97]:
#negative indexing 

Array_AB[:,-2:-4:-1]

array([[ 4,  3],
       [ 9,  8],
       [14, 13],
       [19, 18],
       [24, 23]])

In [98]:
# boolean idexing

Greater_Than_Five = Array_AB > 5

In [100]:
Greater_Than_Five

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [101]:
#all true values
Array_AB[Greater_Than_Five]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [102]:
# where method

drop_under_five = np.where(Array_AB>5, Array_AB,0)

In [103]:
drop_under_five

array([[ 0,  0,  0,  0,  0],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:

drop_under_five_under_twenty = np.logical_and(Array_AB >5, Array_AB <20)

In [115]:
drop_under_five_under_twenty

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [118]:
Array_AB[drop_under_five_under_twenty]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [120]:
array_ab = np.arange(0,100,5)

In [121]:
array_ab

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [123]:
array_ab=array_ab.reshape(4,5)

In [124]:
array_ab

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [126]:
array_ab[:,-1]

array([20, 45, 70, 95])

In [127]:
array_a_abv_50 = array_ab[array_ab>50]

In [128]:
array_a_abv_50

array([55, 60, 65, 70, 75, 80, 85, 90, 95])

In [131]:
array_a_abv_50[0:len(array_a_abv_50):3]

array([55, 70, 85])

In [134]:
array_ab[0:5:2]

array([[ 0,  5, 10, 15, 20],
       [50, 55, 60, 65, 70]])

In [141]:
print(array_ab)
np.where(array_ab>5, array_ab*2, -1 )

[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


array([[ -1,  -1,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [142]:
array_ab

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [148]:
print(array_ab[:,-1:-6:-1])

[[20 15 10  5  0]
 [45 40 35 30 25]
 [70 65 60 55 50]
 [95 90 85 80 75]]


In [149]:
drop_over_20_under_75 = np.logical_and(array_ab >20, array_ab <75)

In [155]:
drop_over_20_under_75 = array_ab[drop_over_20_under_75]

In [157]:
drop_over_20_under_75.reshape(2,5)

array([[25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70]])

In [159]:
# numpy math

array_a = np.array([[1,2],[3,4]])
array_b = np.array([[2,2],[6,6]])

In [161]:
#single array operations 

array_a.sum()

10

In [162]:
array_a.sum(axis=1)

array([3, 7])

In [163]:
array_a.sum(axis=0)

array([4, 6])

In [164]:
array_a.cumsum()

array([ 1,  3,  6, 10])

In [165]:
array_a.prod()

24

In [167]:
array_a.cumprod()

array([ 1,  2,  6, 24])

In [168]:
# two array maths

array_a+array_b

array([[ 3,  4],
       [ 9, 10]])

In [169]:
array_a-array_b

array([[-1,  0],
       [-3, -2]])

In [170]:
array_a*array_b

array([[ 2,  4],
       [18, 24]])

In [173]:
array_a/array_b

array([[0.5       , 1.        ],
       [0.5       , 0.66666667]])

In [174]:
np.dot(array_a,array_b)

array([[14, 14],
       [30, 30]])

In [181]:
array_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b = np.array([[2,2,2],[3,4,5],[6,7,8]])
array_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
array_a.sum(axis=1)

array([ 6, 15, 24])

In [177]:
array_a.sum(axis=0)

array([12, 15, 18])

In [179]:
#takes the maximum and minimum (precents the substraction)
array_a.ptp(axis=1)

array([2, 2, 2])

In [182]:
array_a.ptp()#highest number - lowest number

8

In [184]:
array_a.min()

1

In [185]:
array_a.max()

9

In [186]:
array_a.mean()

5.0

In [187]:
array_b.mean()

4.333333333333333

In [190]:
np.power(array_a,array_b)# base and exponent

array([[       1,        4,        9],
       [      64,      625,     7776],
       [  117649,  2097152, 43046721]])

In [191]:
np.power(array_a, 2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [192]:
c = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [193]:
array_a/array_b/c

array([[0.5       , 1.        , 1.5       ],
       [0.66666667, 0.625     , 0.6       ],
       [0.38888889, 0.38095238, 0.375     ]])

In [196]:
d = array_a*array_b*c

In [197]:
d.ptp()

214

In [198]:
d.ptp(1)

array([ 4, 36, 90])

In [205]:
#numpy broadcasting

array_a = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
array_a

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [206]:
array_b = np.array([0,1,2,3])
array_b

array([0, 1, 2, 3])

In [203]:
array_c = np.array([[1],[2],[3]])

In [204]:
array_a+array_b

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [208]:
array_a+array_c

array([[2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6]])

In [209]:
#atleast one dimension should match

In [210]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,2,1]])
a+b

array([[ 4,  4,  4],
       [ 7,  7,  7],
       [10, 10, 10]])

In [212]:
c = np.array([[3],[2],[1]])
a+c

array([[ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [215]:
e = np.ones((5,5),dtype=)

In [216]:
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [218]:
f = np.array([[1],[2],[3],[4],[5]])

In [219]:
e*f

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])